(define (pascal-triangle row col)
  (cond ((> col row) 0)
        ((= col 1) 1)
        ((= col row) 1)
        (else (+
                (pascal-triangle (- row 1) (- col 1))
                (pascal-triangle (- row 1) col)))))

; Pascal's triangle, the top most is at (col=1, row=1) 
;
;~~~~~~~1
;~~~~~~1~~1
;~~~~~1~~2~~1
;~~~~1~~3~~3~~1
;~~1~~4~~6~~4~~1
;
; Process generated by pascal-triangle procedure (aliased as f to save spave)
; when evaluating (pascal-triangle 4 2)
;          _(f 4 2)_
;         /         \
; (+ (f 3 1)       (f 3 2))
;       |              |
;       1    (+ (f 2 1) (2 2))
;                   |     |
;                   1     1
