;;; Process generated by the pow procedure in evaluating (pow 2 4)
;;;
;;; (pow 2 4)
;;; (* 2 (pow 2 3))
;;; (* 2 (* 2 (pow 2 2)))
;;; (* 2 (* 2 (* 2 (pow 2 1))))
;;; (* 2 (* 2 (* 2 (* 2 (pow 2 0)))))
;;; (* 2 (* 2 (* 2 (* 2 1))))
;;; (* 2 (* 2 (* 2 2)))
;;; (* 2 (* 2 4))
;;; (* 2 8)
;;; 16

(define (pow b n)
  (if (= n 0)
      1
      (* b (pow b (- n 1)))))
