;;; Process generated by the pow procedure in evaluating (pow 2 4)
;;;
;;; (iter 1 4)
;;; (iter 2 3)
;;; (iter 4 2)
;;; (iter 8 1)
;;; (iter 16 0)
;;; 16
         
(define (pow b n)
  (define (iter product count)
    (if (= count 0)
	product
	(iter
	 (* b product)
	 (- count 1))))
  (iter 1 n))
